name: 'Release to PlayStore'
description: 'GitHub Action to release android app to PlayStore'
author: 'bijaykumarpun'
branding: 
  icon: 'package'
  color: 'purple'
inputs:
  packageName:
    description: 'Application package name'
    required: true
    # default: 'com.example.app'
  serviceAccountJson:
    description: 'Service account JSON file content'
    required: true
    # default: '{}'
  releaseFileDir:
    description: 'Release file directory'
    required: true
    # default: './'
  track:
    description: 'Release track'
    required: false
    # default: 'internalSharing'
  mappingFileDir:
    description: 'Mapping file directory'
    required: false
    # default: './'


runs:
  using: 'node16'
  main: 'dist/index.js'
